// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oruyifeujorusczvljdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ydXlpZmV1am9ydXNjenZsamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MDgyMjUsImV4cCI6MjA3NDE4NDIyNX0.PmKV54iR-oEo7IGrEUouYm8OzqsgSmdoOpZbRDb3I44";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});